spring:
  application:
    name: staymanager

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

  datasource:
    url: ${DATABASE_URL_LOCALHOST}
    username: ${DATABASE_USERNAME_REGULAR}
    password: ${DATABASE_PASSWORD_REGULAR}

server:
  port: ${PORT}


jwt:
  secret: ${JWT_SECRET}
  acccess:
    expiration: 1000 * 60 * 60 * 24
  refresh:
    expiration: 1000 * 60 * 60 * 24 * 7
  header:
    name: ${JWT_HEADER}